[[collection]]
type = "card_simple"
title = "Quantum Computing Now podcast"
link = "https://creators.spotify.com/pod/profile/quantumcomputingnow/episodes/Compilers--Compilers--Compilers--with-John-Long-QuEra-e3ov367"
content = "Compilers, Compilers, Compilers!"
date = "Sep 2026"

[[collection]]
type = "card_simple"
title = "Beaver Works Summer Institute @ MIT"
link = "https://bwsi.mit.edu/"
content = "Parallels in the Stack for Quantum and Classical Computation"
date = "Jul 2026"