[[collection]]
type = "card_simple"
title = "Beaver Works Summer Institute @ MIT"
link = "https://bwsi.mit.edu/"
content = "Parallels in the Stack for Quantum and Classical Computation"
date = "July 2026"
